default :
	@echo MAKING... Open PHIGS library
	(cd libphigs; make)
	@echo MAKING... binaries
	(cd bin; make)

clean :
	@echo CLEANING... Open PHIGS library
	(cd libphigs;  make clean)
	@echo CLEANING... binaries
	(cd bin; make clean)

